### ISSUE TITLE
License

### ISSUE THREAD

**Issue by slybit** [chrku/whitebox_crypto#2]
Hello,

I could not find an email address, so I am abusing this to communicate with you.

I would like to use your implementation as a basis for a custom whitebox scheme. Would it be possible to adapt your license to make this possible? 
For example the ISC license? https://en.wikipedia.org/wiki/ISC_license

You say that NTL forces you to go to GPL, but that is not longer the case, NTL is now licensed a LGPL, allowing you to choose any license you want.

I would greatly appreciate it!

Regards,
Stefaan

**Comment by chrku** [comment]
Sure, no problem.

**Comment by slybit** [comment]
Hey, thanks a lot! "Issue can be closed :-)"
